### ISSUE TITLE
Class pointer missing

### ISSUE THREAD

**Issue by qwelias** [inunorii/Elden-Ring-CT-TGA#1]
When editing stats we should consider character starting class too, otherwise the tinkering can be detected if certain stat is lower than initial class value. Would be great if a pointer can be added

**Comment by inunorii** [comment]
Added in v0.3. [bdced05](https://github.com/inunorii/Elden-Ring-CT-TGA/commit/bdced05db89968c8d84f192998210430cdb54291)

**Comment by qwelias** [comment]
Thanks!
