### ISSUE TITLE
Game update breaks the usability

### ISSUE THREAD

**Issue by Luism0** [inunorii/Elden-Ring-CT-TGA#10]
Not sure if can be done, but every game update leaves the table freezed and unusable.

**Comment by inunorii** [comment]
I'm not sure what you're asking for. The current version of the table is tested to work for App ver 1.03.1 and 1.03.2 of Elden Ring.
If you're playing an outdated version of the game for whatever reason, try one of the older tables in the Releases section.

**Comment by inunorii** [comment]
No further info given, closing.
