### ISSUE TITLE
"Give all limited quantity consumables x99" MassItemGib script doesn't work

### ISSUE THREAD

**Issue by Mar-Veloz** [inunorii/Elden-Ring-CT-TGA#15]
The "Give all limited quantity consumables x99" script is meant to give 99 of the pot/perfume items, but doesn't actually work due to the fact that the number of pots/perfumes you can hold is limited by the number of cracked pots/ritual pots/perfume bottles you have. Given that fact, it seems unlikely to ever be able to work, and should probably just be removed.

**Comment by inunorii** [comment]
Anything exceeding what your inventory can hold shold be going into storage, which does work for those consumables.

**Comment by Mar-Veloz** [comment]
Oh, I didn't notice that, my bad.

I still find it less useful/convenient to have to go back to a fire to pick them up rather than just giving myself crafting materials so I can make them on demand, so I would still personally lean towards removing the script. But I recognize that's more a matter of personal preference, so feel free to close the issue if you disagree.

**Comment by escape0707** [comment]
> Oh, I didn't notice that, my bad.
> 
> 
> 
> I still find it less useful/convenient to have to go back to a fire to pick them up rather than just giving myself crafting materials so I can make them on demand, so I would still personally lean towards removing the script. But I recognize that's more a matter of personal preference, so feel free to close the issue if you disagree.

There is an auto fill feature in the game, when you invade or rest at a grace, the consumables and even reinforcement materials will fill up to the limit you can hold.
