### ISSUE TITLE
Flasks of 'X' missing in drop down

### ISSUE THREAD

**Issue by 13DM** [inunorii/Elden-Ring-CT-TGA#17]
Flask of Cerulean Tears and Crimson Tears are missing from the drop down in ItemGib. Viewing the table I see them there on the GOODS_TABLE ID 1000-1025 and 1050-1075. 

Using the Details tab, I am able to use ItemGib using the correct values (40000433 for Flask of Cerulean Tears +12)

**Comment by inunorii** [comment]
They've been removed from the ItemGib dropdown intentionally.

**Comment by 13DM** [comment]
All good, just wanted to verify if it was intentional or not. Appreciate the info.
