### ISSUE TITLE
Elden Ring CE table

### ISSUE THREAD

**Issue by Hemptet** [inunorii/Elden-Ring-CT-TGA#5]
So the table is not pulling up for me. I have the "Open - The Grand Achrives v0.3.1" but it just highlights green and when checking the box nothing happens

**Comment by inunorii** [comment]
1. Is your game up-to-date and unmodified?
2. Did you make sure to disable EasyAntiCheat in some way?
3. Are you running the game via eldenring.exe?

To cover 2. and 3. you can use LukeYui's [Offline Launcher](https://www.nexusmods.com/eldenring/mods/98).

**Comment by inunorii** [comment]
Solved on discord. EasyAntiCheat was the issue.
