### ISSUE TITLE
the new version doesnt work

### ISSUE THREAD

**Issue by eezie23** [inunorii/Elden-Ring-CT-TGA#6]
cant activate the table, somehow it cant even checklist the open script thingy on cheat engine

**Comment by inunorii** [comment]
Please provide more info, so I can try to help you.

1. Is your game up-to-date and unmodified?
2. Did you make sure to disable EasyAntiCheat in some way?
3. Are you running the game via eldenring.exe?

To cover 2. and 3. you can use LukeYui's [Offline Launcher](https://www.nexusmods.com/eldenring/mods/98).

**Comment by eezie23** [comment]
1. Yes
2. Yes, i did. I did the rename "elden ring.exe" to "start_protected_game.exe" thingy to avoid EAC
3. I run it via steam

**Comment by inunorii** [comment]
Your method of avoiding EAC is no longer supported by this cheat table. It specifically looks for "eldenring.exe".
You should try the [Offline Launcher](https://www.nexusmods.com/eldenring/mods/98) or just copy over the script from the old table that allowed using that method.

**Comment by eezie23** [comment]
it works, thank you
