### ISSUE TITLE
Unlimited HP doesn't work

### ISSUE THREAD

**Issue by vczh** [inunorii/Elden-Ring-CT-TGA#7]
**Version**: should be 1.03, Steam updated my game today.

**Start**: by creating steam_appid.txt:

-  Start eldenring.exe
- Load the map
- Open cheat engine and load the table (downloaded from 902a833)
- Attach process

**Repro**:

- Expand hero / character flags / unlimited HP
- Check unlimited HP
- Change the value from `Off` to `On`
- Find an empty and make it attack me

HP decreases unexpectedly.

**Comment by escape0707** [comment]
Holy Moly, the actual vczh. XD
